### ISSUE TITLE
How to set a default state

### ISSUE THREAD

**Issue by noeszc** [vvgomes/redux-definer#1]
It is a clean replacement of the common boilerplate, but I would like to know how to pass a default state, other than when the store is created, so as not to have conflicts with other libraries such as redux-persist.

Thanks.

**Comment by vvgomes** [comment]
That's a good question. However, passing a default state to the `defineReducer` is not in scope since that would conflict with the `createStore` interface. (What would be the effect if people set a different default state to both?)

Thanks!
